### Auth: POST Generar token

POST  https://node-mongo-api-nine.vercel.app/auth
Content-Type: application/json

{
  "email": "andrea.soncco.c@gmail.com",
  "password": "ElijoSerFeliz27"
}

### ORDERS
### Orders: GET Listar ordenes

GET  https://node-mongo-api-nine.vercel.app/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE

### Orders: POST Crear una orden determinada

POST  https://node-mongo-api-nine.vercel.app/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE
Content-Type: application/json

{
  "userId": 4,
  "client": "Katie Bouman",
  "products": [
    {
      "qty": 1,
      "product": {
        "id": 1331,
        "name": "café americano",
        "price": "5",
        "image": "https://perfectdailygrind.com/wp-content/uploads/2020/08/Filter-or-Americano-2.jpg",
        "type": "almuerzo y cena"
      }
    },
    {
      "qty": 1,
      "product": {
        "id": 2341,
        "name": "agua 500ml",
        "price": "5",
        "image": "https://wongfood.vtexassets.com/arquivos/ids/252192-800-auto?v=636754932463500000&width=800&height=auto&aspect=true",
        "type": "desayuno"
      }
    }
  ]
}

### Orders/{OrderId}: GET Mostrar una orden determinada

GET  https://node-mongo-api-nine.vercel.app/orders/65789dde4b6f55427d06a2f8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE

### Orders/{OrderId}: PUT Modificar una orden determinada

PUT  https://node-mongo-api-nine.vercel.app/orders/65789dde4b6f55427d06a2f8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE
Content-Type: application/json

{
  "userId": 4,
  "client": "Katie Bouman",
  "products": [
    {
      "qty": 1,
      "product": {
        "id": 1331,
        "name": "café americano",
        "price": "5",
        "image": "https://perfectdailygrind.com/wp-content/uploads/2020/08/Filter-or-Americano-2.jpg",
        "type": "desayuno"
      }
    },
    {
      "qty": 1,
      "product": {
        "id": 2341,
        "name": "agua 500ml",
        "price": "5",
        "image": "https://wongfood.vtexassets.com/arquivos/ids/252192-800-auto?v=636754932463500000&width=800&height=auto&aspect=true",
        "type": "almuerzo y cena"
      }
    }
  ],
  "status": "delivered"
}

### Orders/{OrderId}: DELETE Eliminar una orden determinada

DELETE  https://node-mongo-api-nine.vercel.app/orders/65789dde4b6f55427d06a2f8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE

### PRODUCTS
### Products: GET Listar productos

GET  https://node-mongo-api-nine.vercel.app/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE

### Products: POST Crear un producto determinado

POST  https://node-mongo-api-nine.vercel.app/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE
Content-Type: application/json

{
  "id": 2352,
  "name": "gaseosa 750ml",
  "price": 10,
  "image": "https://plazavea.vteximg.com.br/arquivos/ids/563349-512-512/20201608.jpg",
  "type": "desayuno"
}

### Products/{ProductId}: GET Mostrar un producto determinado

GET  https://node-mongo-api-nine.vercel.app/products/6578a05a4b6f55427d06a2f9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE

### Products/{ProductId}: PUT Modificar un producto determinado

PUT  https://node-mongo-api-nine.vercel.app/products/6578a05a4b6f55427d06a2f9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE
Content-Type: application/json

{
  "id": 2352,
  "name": "gaseosa 750ml",
  "price": 10,
  "image": "https://plazavea.vteximg.com.br/arquivos/ids/563349-512-512/20201608.jpg",
  "type": "almuerzo y cena"
}

### Products/{ProductId}: DELETE Eliminar un producto determinado

DELETE  https://node-mongo-api-nine.vercel.app/products/6578a05a4b6f55427d06a2f9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE

### USERS
### Users: GET Listar usuarias

GET  https://node-mongo-api-nine.vercel.app/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE

### Users: POST Crear una usuaria determinada

POST  https://node-mongo-api-nine.vercel.app/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE
Content-Type: application/json

{
  "id": 2,
  "email": "celso.soncco@gmail.com",
  "password": "nose8nose",
  "roles": { "admin": true }
}

### Users/{UserId}: GET Mostrar una usuaria determinada

GET  https://node-mongo-api-nine.vercel.app/users/6578c8780ba46e8bf3d458a6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE

### Users/{UserId}: PUT Modificar una usuaria determinada

PUT  https://node-mongo-api-nine.vercel.app/users/6578c8780ba46e8bf3d458a6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE
Content-Type: application/json

{
  "email": "celsonca@gmail.com",
  "password": "navidad1727",
  "roles": {
    "admin": true,
    "waiter": true 
  }
}

### Users/{UserId}: DELETE Eliminar una usuaria determinada

DELETE  https://node-mongo-api-nine.vercel.app/users/6578c8780ba46e8bf3d458a6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzFmYjIxNGRhNTA0YWIyZjEyYjRkNiIsInJvbGVzIjp7ImFkbWluIjp0cnVlfSwiaWF0IjoxNzAyMzgzNDA5LCJleHAiOjE3MDI0Njk4MDl9.J-myP4MmfA3HOAz6qaCpu3bTygfIQP_LQ8-d8dHV8EE
